stages:
  - deploy

deploy:
  image: ubuntu:latest
  stage: deploy
  only: 
    - master
  environment:
    name: prod
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no ubuntu@"$SERVER" 'rm -rf /home/ubuntu/hypha-telos-bot/*'
    - scp -P22 -r . ubuntu@"$SERVER":/home/ubuntu/hypha-telos-bot
